# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcpingpb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcpingpb.proto',
  package='grpcpingprt',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10grpcpingpb.proto\x12\x0bgrpcpingprt\"\x15\n\x06Params\x12\x0b\n\x03src\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\")\n\nSwapParams\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\x0c\x32\x8b\x01\n\x0fgRpcPingService\x12\x33\n\x05Hello\x12\x13.grpcpingprt.Params\x1a\x13.grpcpingprt.Status\"\x00\x12\x43\n\tSwapImage\x12\x17.grpcpingprt.SwapParams\x1a\x17.grpcpingprt.SwapParams\"\x00(\x01\x30\x01\x62\x06proto3'
)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='grpcpingprt.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='grpcpingprt.Params.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=54,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='grpcpingprt.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='grpcpingprt.Status.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=80,
)


_SWAPPARAMS = _descriptor.Descriptor(
  name='SwapParams',
  full_name='grpcpingprt.SwapParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='grpcpingprt.SwapParams.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='grpcpingprt.SwapParams.params', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['SwapParams'] = _SWAPPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'grpcpingpb_pb2'
  # @@protoc_insertion_point(class_scope:grpcpingprt.Params)
  })
_sym_db.RegisterMessage(Params)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'grpcpingpb_pb2'
  # @@protoc_insertion_point(class_scope:grpcpingprt.Status)
  })
_sym_db.RegisterMessage(Status)

SwapParams = _reflection.GeneratedProtocolMessageType('SwapParams', (_message.Message,), {
  'DESCRIPTOR' : _SWAPPARAMS,
  '__module__' : 'grpcpingpb_pb2'
  # @@protoc_insertion_point(class_scope:grpcpingprt.SwapParams)
  })
_sym_db.RegisterMessage(SwapParams)



_GRPCPINGSERVICE = _descriptor.ServiceDescriptor(
  name='gRpcPingService',
  full_name='grpcpingprt.gRpcPingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='grpcpingprt.gRpcPingService.Hello',
    index=0,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SwapImage',
    full_name='grpcpingprt.gRpcPingService.SwapImage',
    index=1,
    containing_service=None,
    input_type=_SWAPPARAMS,
    output_type=_SWAPPARAMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCPINGSERVICE)

DESCRIPTOR.services_by_name['gRpcPingService'] = _GRPCPINGSERVICE

# @@protoc_insertion_point(module_scope)
